-- ==============================================================================
-- PIXELNOID LMS - ABSENSI & PRESENSI SCHEMA
-- ==============================================================================
-- Fitur:
-- 1. Pilih murid (bisa banyak -> relasi many-to-many via public.absensi_students)
-- 2. Pilih mentornya siapa (mentor_id UUID -> public.users)
-- 3. Tanggal sesi dan Jamnya (session_date DATE, session_time TEXT)
-- 4. Bukti foto absen (bukti_foto TEXT - URL bukti foto di Supabase Storage)
-- 5. Approval status (pending, approved, rejected) + approver info
-- ==============================================================================

-- 1. Tabel Utama: public.absensi
CREATE TABLE IF NOT EXISTS public.absensi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    mentor_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    session_date DATE NOT NULL,
    session_time TEXT NOT NULL,
    topic TEXT,
    bukti_foto TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'pending', -- 'pending' | 'approved' | 'rejected'
    notes TEXT,
    rejection_reason TEXT,
    approved_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
    approved_at TIMESTAMPTZ
);

-- 2. Tabel Relasi Siswa: public.absensi_students (Mendukung pilih murid banyak)
CREATE TABLE IF NOT EXISTS public.absensi_students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    absensi_id BIGINT NOT NULL REFERENCES public.absensi(id) ON DELETE CASCADE,
    student_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_absensi_student UNIQUE (absensi_id, student_id)
);

-- 3. Indexes untuk optimasi query
CREATE INDEX IF NOT EXISTS idx_absensi_mentor_id ON public.absensi(mentor_id);
CREATE INDEX IF NOT EXISTS idx_absensi_session_date ON public.absensi(session_date DESC);
CREATE INDEX IF NOT EXISTS idx_absensi_status ON public.absensi(status);
CREATE INDEX IF NOT EXISTS idx_absensi_created_at ON public.absensi(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_absensi_students_absensi_id ON public.absensi_students(absensi_id);
CREATE INDEX IF NOT EXISTS idx_absensi_students_student_id ON public.absensi_students(student_id);

-- 4. Storage Bucket untuk Bukti Foto Absen (jika belum ada)
INSERT INTO storage.buckets (id, name, public)
VALUES ('absensi', 'absensi', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage RLS Policies
CREATE POLICY "Public Read Access for Absensi Bucket"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'absensi');

CREATE POLICY "Authenticated users can upload absensi proof"
    ON storage.objects FOR INSERT
    TO authenticated
    WITH CHECK (bucket_id = 'absensi');

CREATE POLICY "Authenticated users can update absensi proof"
    ON storage.objects FOR UPDATE
    TO authenticated
    USING (bucket_id = 'absensi');

CREATE POLICY "Authenticated users can delete absensi proof"
    ON storage.objects FOR DELETE
    TO authenticated
    USING (bucket_id = 'absensi');

-- 5. Row Level Security (RLS) pada Tabel Absensi
ALTER TABLE public.absensi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.absensi_students ENABLE ROW LEVEL SECURITY;

-- Policy Admin & Mentor: Full Access pada absensi
CREATE POLICY "Admin & Mentor full access on absensi"
    ON public.absensi
    FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.users u
            WHERE u.id = auth.uid()
            AND (u.roles @> ARRAY['admin']::text[] OR u.roles @> ARRAY['mentor']::text[])
        )
    );

-- Policy Student: View absensi yang melibatkan dirinya
CREATE POLICY "Student can view absensi they attended"
    ON public.absensi
    FOR SELECT
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.absensi_students ast
            WHERE ast.absensi_id = public.absensi.id
            AND ast.student_id = auth.uid()
        )
    );

-- Policy Admin & Mentor: Full Access pada absensi_students
CREATE POLICY "Admin & Mentor full access on absensi_students"
    ON public.absensi_students
    FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.users u
            WHERE u.id = auth.uid()
            AND (u.roles @> ARRAY['admin']::text[] OR u.roles @> ARRAY['mentor']::text[])
        )
    );

-- Policy Student: View their own absensi_students records
CREATE POLICY "Student can view their own absensi_students"
    ON public.absensi_students
    FOR SELECT
    TO authenticated
    USING (student_id = auth.uid());
