-- ==============================================================================
-- PIXELNOID LMS - MENTORSHIP SESSIONS SCHEMA & MIGRATION
-- ==============================================================================
-- Deskripsi:
-- 1. Membuat / memperbarui tabel 'mentorship_sessions' agar berelasi dengan 'public.users'
-- 2. Mengubah tipe kolom mentor_id dan student_id dari BIGINT ke UUID agar sinkron
--    dengan primary key di tabel public.users.
-- 3. Menambahkan index performa dan Row Level Security (RLS) policies.
-- ==============================================================================

-- 1. Buat tabel jika belum ada (dengan tipe UUID untuk relasi users)
CREATE TABLE IF NOT EXISTS public.mentorship_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    mentor_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    student_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    topic TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Upcoming',
    meeting_link TEXT,
    day TEXT,
    time TEXT,
    type VARCHAR(50) NOT NULL DEFAULT 'main_class'
);

-- Pastikan kolom 'type' ada jika tabel sudah ada sebelumnya
ALTER TABLE public.mentorship_sessions 
    ADD COLUMN IF NOT EXISTS type VARCHAR(50) DEFAULT 'main_class';

-- 2. Jika tabel sudah terlanjur dibuat dengan kolom BIGINT, jalankan alter berikut:
DO $$
BEGIN
    -- Cek tipe data mentor_id, jika bukan uuid ubah ke uuid
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
          AND table_name = 'mentorship_sessions' 
          AND column_name = 'mentor_id' 
          AND data_type <> 'uuid'
    ) THEN
        ALTER TABLE public.mentorship_sessions ALTER COLUMN mentor_id DROP DEFAULT;
        ALTER TABLE public.mentorship_sessions ALTER COLUMN mentor_id TYPE UUID USING NULL;
        ALTER TABLE public.mentorship_sessions 
            ADD CONSTRAINT fk_mentorship_mentor FOREIGN KEY (mentor_id) REFERENCES public.users(id) ON DELETE SET NULL;
    END IF;

    -- Cek tipe data student_id, jika bukan uuid ubah ke uuid
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
          AND table_name = 'mentorship_sessions' 
          AND column_name = 'student_id' 
          AND data_type <> 'uuid'
    ) THEN
        ALTER TABLE public.mentorship_sessions ALTER COLUMN student_id DROP DEFAULT;
        ALTER TABLE public.mentorship_sessions ALTER COLUMN student_id TYPE UUID USING NULL;
        ALTER TABLE public.mentorship_sessions 
            ADD CONSTRAINT fk_mentorship_student FOREIGN KEY (student_id) REFERENCES public.users(id) ON DELETE CASCADE;
    END IF;
END $$;

-- 3. Indexes untuk optimasi query
CREATE INDEX IF NOT EXISTS idx_mentorship_sessions_mentor_id ON public.mentorship_sessions(mentor_id);
CREATE INDEX IF NOT EXISTS idx_mentorship_sessions_student_id ON public.mentorship_sessions(student_id);
CREATE INDEX IF NOT EXISTS idx_mentorship_sessions_status ON public.mentorship_sessions(status);
CREATE INDEX IF NOT EXISTS idx_mentorship_sessions_created_at ON public.mentorship_sessions(created_at DESC);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.mentorship_sessions ENABLE ROW LEVEL SECURITY;

-- Policy Admin & Mentor (Full Access)
CREATE POLICY "Admin & Mentor full access on mentorship_sessions"
    ON public.mentorship_sessions
    FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.users u
            WHERE u.id = auth.uid()
            AND (u.roles @> ARRAY['admin']::text[] OR u.roles @> ARRAY['mentor']::text[])
        )
    );

-- Policy Student (Read-Only sesi miliknya sendiri)
CREATE POLICY "Student can view their own mentorship_sessions"
    ON public.mentorship_sessions
    FOR SELECT
    TO authenticated
    USING (student_id = auth.uid());
