-- ==============================================================================
-- PIXELNOID LMS - RESOURCES SCHEMA & POLICIES (DENGAN FOREIGN KEY CLASS)
-- ==============================================================================
-- Deskripsi:
-- 1. Tabel 'resources' untuk mengelola resource belajar (ebook, template, tools, video, dsb)
-- 2. Kolom 'class_id' sebagai Foreign Key ke tabel 'public.class' (ON DELETE CASCADE)
--    agar setiap kelas memiliki resource yang terisolasi dan terorganisir.
-- 3. Menambahkan indexes untuk pencarian & filtering performa tinggi
-- 4. Menambahkan Row Level Security (RLS) policies
-- ==============================================================================

-- 1. Buat tabel jika belum ada
CREATE TABLE IF NOT EXISTS public.resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT REFERENCES public.class(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    type CHARACTER VARYING(50) DEFAULT 'other',
    url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Jika tabel sudah terlanjur dibuat tanpa kolom class_id, tambahkan kolom & FK:
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
          AND table_name = 'resources' 
          AND column_name = 'class_id'
    ) THEN
        ALTER TABLE public.resources 
            ADD COLUMN class_id BIGINT REFERENCES public.class(id) ON DELETE CASCADE;
    END IF;
END $$;

-- 3. Indexing untuk optimasi query
CREATE INDEX IF NOT EXISTS idx_resources_class_id ON public.resources(class_id);
CREATE INDEX IF NOT EXISTS idx_resources_created_at ON public.resources(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_resources_type ON public.resources(type);

-- 4. Row Level Security (RLS)
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;

-- Drop policies jika sudah ada agar script aman dijalankan ulang (idempotent)
DROP POLICY IF EXISTS "Admin & Mentor full access on resources" ON public.resources;
DROP POLICY IF EXISTS "Authenticated users can view resources" ON public.resources;
DROP POLICY IF EXISTS "Students can view enrolled class resources" ON public.resources;

-- Policy Admin & Mentor (Full Access)
CREATE POLICY "Admin & Mentor full access on resources"
    ON public.resources
    FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.users u
            WHERE u.id = auth.uid()
            AND (u.roles @> ARRAY['admin']::text[] OR u.roles @> ARRAY['mentor']::text[])
        )
    );

-- Policy Student: hanya bisa melihat resource kelas yang dia ikuti (atau resource umum jika class_id null)
CREATE POLICY "Students can view enrolled class resources"
    ON public.resources
    FOR SELECT
    TO authenticated
    USING (
        class_id IS NULL OR EXISTS (
            SELECT 1 FROM public.class_member cm
            WHERE cm.class_id = public.resources.class_id
            AND cm.user_id = auth.uid()
        )
    );
